version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::240977006088:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-1Q2RCTJIGCNFY"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::240977006088:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1UMWB9JA6IQDB"
cloudformation_execution_role = "arn:aws:iam::240977006088:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-7QR13BXXAVH0"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-i5f81jlagtqg"
image_repository = ""
region = "us-east-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::240977006088:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-6RNK9QF5P4P7"
cloudformation_execution_role = "arn:aws:iam::240977006088:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-T773V87C7S8N"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-eqa7ck1yzdg"
image_repository = ""
region = "ap-south-1"
